# Generated by Django 4.2.1 on 2023-05-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField()),
                ('image_dimensions', models.CharField(max_length=32)),
                ('num_outputs', models.IntegerField()),
                ('num_inference_steps', models.PositiveIntegerField()),
                ('guidance_scale', models.FloatField()),
                ('scheduler', models.CharField(max_length=128)),
                ('seed', models.BigIntegerField()),
                ('style', models.CharField(max_length=64)),
                ('saturation', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outputs')),
                ('is_public', models.BooleanField(default=False)),
                ('favorite_count', models.IntegerField(default=0)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artemis.input')),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artemis.user'),
        ),
    ]
