# Generated by Django 4.2.1 on 2023-05-21 00:38

import artemis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='image',
            field=models.ImageField(upload_to=artemis.models.Output.upload_to),
        ),
    ]
