# Generated by Django 4.2.1 on 2023-05-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0002_alter_output_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='replicate_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='saturation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='style',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outputs', to='artemis.input'),
        ),
    ]
