# Generated by Django 4.2.1 on 2023-06-03 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_artemisuser_alter_input_user_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artemisuser",
            name="id",
        ),
        migrations.AlterField(
            model_name="artemisuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
