# Generated by Django 4.2.1 on 2023-06-08 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_profile_alter_input_user_delete_artemisuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="input",
            old_name="color",
            new_name="color_value",
        ),
    ]
