# Generated by Django 4.2.1 on 2023-06-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_color_input_color_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="color_value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
