# Generated by Django 4.2.1 on 2023-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_input_color_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="color_value",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
