# Generated by Django 4.2.1 on 2023-06-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_output_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.output"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.profile"
                    ),
                ),
            ],
        ),
    ]
