# Generated by Django 4.2.1 on 2023-06-22 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="output_id",
            new_name="output",
        ),
        migrations.RenameField(
            model_name="favorite",
            old_name="user_id",
            new_name="profile",
        ),
    ]
