# Generated by Django 4.2.1 on 2023-06-22 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_rename_output_id_favorite_output_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorited_by", through="api.Favorite", to="api.output"
            ),
        ),
    ]
